#+TITLE: libCat 🐈‍⬛
#+AUTHOR: Conscat
#+OPTIONS: ^:{}
#+STARTUP: fold

libCat is a non-POSIX compliant C++26 runtime.
It has no pthreads nor =malloc()=, and by extension no exceptions.
It has type-safe arithmetic, SIMD, fast syscalls, CRTP interfaces,

* Building
libCat requires a recent development version of Clang 23 from the =trunk= branch.
It is tested on GitHub using the [official nightly](https://apt.llvm.org/) distribution,
so this is certainly servicable for any local or downstream development.
Compiling libCat is only routinely tested using =ninja=, but other build systems may work.
The ="Ninja Multi-Config"= generator is also supported.
A reasonably recent version of CMake is required (at least 3.28 is recommended).

#+BEGIN_SRC sh
  $ export CXX=clang++-23
  $ cmake -B build/ -G 'Ninja'
  $ cmake --build build/
  $ ./build/tests/unit_tests # or ctest --test-dir/build --output-on-failure
#+END_SRC

The =.clang-format= and =.clang-tidy= configurations are only compatible with correspondingly
recent builds of clang-tools.

* Tools
libCat provides several developer utilities. They are organized in the =cmake/=
subdirectory.

** =cat-format=
#+BEGIN_SRC
  $ cmake --build build/ --target cat-format
#+END_SRC
Runs =clang-format= in place on every libCat implementation source and public
header. The files which changed are reported afterwards.

CMake auto-discovers an appropriate version of =clang-format= on =PATH=,
if one exists. Override its choice=-DCAT_CLANG_FORMAT_PATH=/path/to/clang-format=
at configure time.
The =.clang-format= and =.clang-tidy= configurations are only compatible with recent builds of clang-tools from the =main= branch.
