#pragma once

// clang-format off
#define CAT_QUANTITY_FORMAT_TESTS(apply) \
   apply(gradian, "1 grad", "1E0 grad") \
   apply(metre, "1 m", "1E0 m") \
   apply(second, "1 s", "1E0 s") \
   apply(gram, "1 g", "1E0 g") \
   apply(kilogram, "1 kg", "1E0 kg") \
   apply(ampere, "1 A", "1E0 A") \
   apply(kelvin, "1 K", "1E0 K") \
   apply(mole, "1 mol", "1E0 mol") \
   apply(candela, "1 cd", "1E0 cd") \
   apply(radian, "1 rad", "1E0 rad") \
   apply(steradian, "1 sr", "1E0 sr") \
   apply(hertz, "1 Hz", "1E0 Hz") \
   apply(attohertz, "1 aHz", "1E0 aHz") \
   apply(femtohertz, "1 fHz", "1E0 fHz") \
   apply(picohertz, "1 pHz", "1E0 pHz") \
   apply(nanohertz, "1 nHz", "1E0 nHz") \
   apply(microhertz, "1 uHz", "1E0 uHz") \
   apply(millihertz, "1 mHz", "1E0 mHz") \
   apply(kilohertz, "1 kHz", "1E0 kHz") \
   apply(megahertz, "1 MHz", "1E0 MHz") \
   apply(gigahertz, "1 GHz", "1E0 GHz") \
   apply(terahertz, "1 THz", "1E0 THz") \
   apply(petahertz, "1 PHz", "1E0 PHz") \
   apply(exahertz, "1 EHz", "1E0 EHz") \
   apply(newton, "1 N", "1E0 N") \
   apply(pascal, "1 Pa", "1E0 Pa") \
   apply(joule, "1 J", "1E0 J") \
   apply(watt, "1 W", "1E0 W") \
   apply(coulomb, "1 C", "1E0 C") \
   apply(volt, "1 V", "1E0 V") \
   apply(farad, "1 F", "1E0 F") \
   apply(ohm, "1 ohm", "1E0 ohm") \
   apply(siemens, "1 S", "1E0 S") \
   apply(weber, "1 Wb", "1E0 Wb") \
   apply(tesla, "1 T", "1E0 T") \
   apply(henry, "1 H", "1E0 H") \
   apply(celsius, "1 degC", "1E0 degC") \
   apply(lumen, "1 lm", "1E0 lm") \
   apply(lux, "1 lx", "1E0 lx") \
   apply(becquerel, "1 Bq", "1E0 Bq") \
   apply(gray, "1 Gy", "1E0 Gy") \
   apply(sievert, "1 Sv", "1E0 Sv") \
   apply(katal, "1 kat", "1E0 kat") \
   apply(square_metre, "1 m^2", "1E0 m^2") \
   apply(cubic_metre, "1 m^3", "1E0 m^3") \
   apply(reciprocal_metre, "1 1/m", "1E0 1/m") \
   apply(metre_per_second, "1 m/s", "1E0 m/s") \
   apply(metre_per_second_squared, "1 m/s^2", "1E0 m/s^2") \
   apply(kilogram_per_cubic_metre, "1 kg/m^3", "1E0 kg/m^3") \
   apply(mole_per_cubic_metre, "1 mol/m^3", "1E0 mol/m^3") \
   apply(ampere_per_square_metre, "1 A/m^2", "1E0 A/m^2") \
   apply(volt_per_metre, "1 kg*m/A*s^3", "1E0 kg*m/A*s^3") \
   apply(coulomb_per_square_metre, "1 A*s/m^2", "1E0 A*s/m^2") \
   apply(ampere_per_metre, "1 A/m", "1E0 A/m") \
   apply(joule_per_kelvin, "1 kg*m^2/K*s^2", "1E0 kg*m^2/K*s^2") \
   apply(watt_per_square_metre, "1 kg/s^3", "1E0 kg/s^3") \
   apply(minute, "1 min", "1E0 min") \
   apply(hour, "1 h", "1E0 h") \
   apply(day, "1 d", "1E0 d") \
   apply(degree, "1 deg", "1E0 deg") \
   apply(arcminute, "1 arcmin", "1E0 arcmin") \
   apply(arcsecond, "1 arcsec", "1E0 arcsec") \
   apply(revolution, "1 rev", "1E0 rev") \
   apply(hectare, "1 ha", "1E0 ha") \
   apply(litre, "1 L", "1E0 L") \
   apply(tonne, "1 t", "1E0 t") \
   apply(dalton, "1 Da", "1E0 Da") \
   apply(astronomical_unit, "1 au", "1E0 au") \
   apply(nautical_mile, "1 nmi", "1E0 nmi") \
   apply(knot, "1 kn", "1E0 kn") \
   apply(angstrom, "1 angstrom", "1E0 angstrom") \
   apply(electronvolt, "1 eV", "1E0 eV") \
   apply(bar, "1 bar", "1E0 bar") \
   apply(parsec, "1 pc", "1E0 pc") \
   apply(solar_mass, "1 M_SUN", "1E0 M_SUN") \
   apply(terrestrial_mass, "1 M_EARTH", "1E0 M_EARTH") \
   apply(jovian_mass, "1 M_JUP", "1E0 M_JUP") \
   apply(astronomical_day, "1 D", "1E0 D") \
   apply(sidereal_day, "1 D_sid", "1E0 D_sid") \
   apply(julian_year, "1 a", "1E0 a") \
   apply(tropical_year, "1 a_trop", "1E0 a_trop") \
   apply(century, "1 c", "1E0 c") \
   apply(millennium, "1 ka", "1E0 ka") \
   apply(lunar_distance, "1 LD", "1E0 LD") \
   apply(light_year, "1 ly", "1E0 ly") \
   apply(jansky, "1 Jy", "1E0 Jy") \
   apply(pound, "1 lb", "1E0 lb") \
   apply(ounce, "1 oz", "1E0 oz") \
   apply(dram, "1 dr", "1E0 dr") \
   apply(grain, "1 gr", "1E0 gr") \
   apply(yard, "1 yd", "1E0 yd") \
   apply(foot, "1 ft", "1E0 ft") \
   apply(inch, "1 in", "1E0 in") \
   apply(pica, "1 P", "1E0 P") \
   apply(point, "1 p", "1E0 p") \
   apply(mil, "1 mil", "1E0 mil") \
   apply(twip, "1 twip", "1E0 twip") \
   apply(mile, "1 mi", "1E0 mi") \
   apply(league, "1 lea", "1E0 lea") \
   apply(fathom, "1 ftm", "1E0 ftm") \
   apply(mile_per_hour, "1 mph", "1E0 mph") \
   apply(poundal, "1 pdl", "1E0 pdl") \
   apply(pound_force, "1 lbf", "1E0 lbf") \
   apply(kip, "1 klbf", "1E0 klbf") \
   apply(psi, "1 psi", "1E0 psi") \
   apply(mechanical_horsepower, "1 hp(I)", "1E0 hp(I)") \
   apply(hand, "1 hh", "1E0 hh") \
   apply(barleycorn, "1 Bc", "1E0 Bc") \
   apply(thou, "1 th", "1E0 th") \
   apply(imperial_chain, "1 ch", "1E0 ch") \
   apply(imperial_furlong, "1 fur", "1E0 fur") \
   apply(imperial_cable, "1 cb", "1E0 cb") \
   apply(imperial_link, "1 li", "1E0 li") \
   apply(imperial_rod, "1 rd", "1E0 rd") \
   apply(perch, "1 perch", "1E0 perch") \
   apply(rood, "1 rood", "1E0 rood") \
   apply(imperial_acre, "1 acre", "1E0 acre") \
   apply(imperial_gallon, "1 gal", "1E0 gal") \
   apply(imperial_quart, "1 qt", "1E0 qt") \
   apply(imperial_pint, "1 pt", "1E0 pt") \
   apply(imperial_gill, "1 gi", "1E0 gi") \
   apply(imperial_fluid_ounce, "1 fl oz", "1E0 fl oz") \
   apply(stone, "1 st", "1E0 st") \
   apply(quarter, "1 qr", "1E0 qr") \
   apply(long_hundredweight, "1 cwt", "1E0 cwt") \
   apply(imperial_ton, "1 t", "1E0 t") \
   apply(centimetre, "1 cm", "1E0 cm") \
   apply(gal, "1 Gal", "1E0 Gal") \
   apply(dyne, "1 dyn", "1E0 dyn") \
   apply(erg, "1 erg", "1E0 erg") \
   apply(barye, "1 Ba", "1E0 Ba") \
   apply(poise, "1 P", "1E0 P") \
   apply(stokes, "1 St", "1E0 St") \
   apply(kayser, "1 K", "1E0 K") \
   apply(fermi, "1 fm", "1E0 fm") \
   apply(barn, "1 b", "1E0 b") \
   apply(eplus, "1 e+", "1E0 e+") \
   apply(atmosphere, "1 atm", "1E0 atm") \
   apply(gauss, "1 G", "1E0 G") \
   apply(curie, "1 Ci", "1E0 Ci") \
   apply(bit, "1 bit", "1E0 bit") \
   apply(octet, "1 o", "1E0 o") \
   apply(byte, "1 B", "1E0 B") \
   apply(erlang, "1 E", "1E0 E") \
   apply(baud, "1 Bd", "1E0 Bd") \
   apply(kilobit, "1 kbit", "1E0 kbit") \
   apply(megabit, "1 Mbit", "1E0 Mbit") \
   apply(gigabit, "1 Gbit", "1E0 Gbit") \
   apply(terabit, "1 Tbit", "1E0 Tbit") \
   apply(kibibit, "1 Kibit", "1E0 Kibit") \
   apply(mebibit, "1 Mibit", "1E0 Mibit") \
   apply(gibibit, "1 Gibit", "1E0 Gibit") \
   apply(tebibit, "1 Tibit", "1E0 Tibit") \
   apply(pebibit, "1 Pibit", "1E0 Pibit") \
   apply(exbibit, "1 Eibit", "1E0 Eibit") \
   apply(kilobyte, "1 kB", "1E0 kB") \
   apply(megabyte, "1 MB", "1E0 MB") \
   apply(gigabyte, "1 GB", "1E0 GB") \
   apply(terabyte, "1 TB", "1E0 TB") \
   apply(kibibyte, "1 KiB", "1E0 KiB") \
   apply(mebibyte, "1 MiB", "1E0 MiB") \
   apply(gibibyte, "1 GiB", "1E0 GiB") \
   apply(tebibyte, "1 TiB", "1E0 TiB") \
   apply(pebibyte, "1 PiB", "1E0 PiB") \
   apply(exbibyte, "1 EiB", "1E0 EiB") \
   apply(natural_electronvolt, "1 eV", "1E0 eV") \
   apply(gigaelectronvolt, "1 GeV", "1E0 GeV") \
   apply(inverse_gigaelectronvolt, "1 1/GeV", "1E0 1/GeV") \
   apply(gigaelectronvolt_squared, "1 GeV^2", "1E0 GeV^2") \
   apply(pixel, "1 px", "1E0 px") \
   apply(horizontal_pixel, "1 px", "1E0 px") \
   apply(vertical_pixel, "1 px", "1E0 px") \
   apply(femtosecond, "1 fs", "1E0 fs") \
   apply(nanosecond, "1 ns", "1E0 ns") \
   apply(microsecond, "1 us", "1E0 us") \
   apply(millisecond, "1 ms", "1E0 ms") \
   apply(pica_us, "1 pica(us)", "1E0 pica(us)") \
   apply(point_us, "1 point(us)", "1E0 point(us)") \
   apply(point_dtp, "1 point(dtp)", "1E0 point(dtp)") \
   apply(pica_dtp, "1 pica(dtp)", "1E0 pica(dtp)") \
   apply(didot_point, "1 point(didot)", "1E0 point(didot)") \
   apply(cicero, "1 cicero", "1E0 cicero") \
   apply(q, "1 Q", "1E0 Q") \
   apply(h, "1 H", "1E0 H") \
   apply(tex_point, "1 point(tex)", "1E0 point(tex)") \
   apply(us_cable, "1 cb(us)", "1E0 cb(us)") \
   apply(us_survey_foot, "1 ft(us)", "1E0 ft(us)") \
   apply(us_survey_mile, "1 mi(us)", "1E0 mi(us)") \
   apply(us_link, "1 li", "1E0 li") \
   apply(us_rod, "1 rd", "1E0 rd") \
   apply(us_chain, "1 ch", "1E0 ch") \
   apply(us_furlong, "1 fur", "1E0 fur") \
   apply(us_acre, "1 acre", "1E0 acre") \
   apply(section, "1 section", "1E0 section") \
   apply(us_gallon, "1 gal", "1E0 gal") \
   apply(pottle, "1 pot", "1E0 pot") \
   apply(us_quart, "1 qt", "1E0 qt") \
   apply(us_pint, "1 pt", "1E0 pt") \
   apply(cup, "1 c", "1E0 c") \
   apply(us_gill, "1 gi", "1E0 gi") \
   apply(us_fluid_ounce, "1 fl oz", "1E0 fl oz") \
   apply(tablespoon, "1 tbsp", "1E0 tbsp") \
   apply(teaspoon, "1 tsp", "1E0 tsp") \
   apply(barrel, "1 bbl", "1E0 bbl") \
   apply(oil_barrel, "1 bbl(oil)", "1E0 bbl(oil)") \
   apply(bushel, "1 bu", "1E0 bu") \
   apply(peck, "1 pk", "1E0 pk") \
   apply(dry_gallon, "1 gal(dry)", "1E0 gal(dry)") \
   apply(dry_quart, "1 qt(dry)", "1E0 qt(dry)") \
   apply(dry_pint, "1 pt(dry)", "1E0 pt(dry)") \
   apply(short_hundredweight, "1 cwt", "1E0 cwt") \
   apply(us_ton, "1 t", "1E0 t") \
   apply(pennyweight, "1 dwt", "1E0 dwt") \
   apply(troy_ounce, "1 oz t", "1E0 oz t") \
   apply(troy_pound, "1 lb t", "1E0 lb t") \
   apply(inch_of_mercury, "1 inHg", "1E0 inHg")
// clang-format on
