#!/usr/bin/env bash
# clang-repl-libcat: Launch clang-repl with libCat ready for use.
#
# Generated by `cmake/cat_shared.cmake` when `CAT_BUILD_SHARED=ON`. Reads
# the matching compile flags out of `compile_commands.json` so the REPL
# parses the same C++26 / freestanding / SIMD-intrinsic dialect the
# library was built against, then pre-loads `libcat.so` via `%lib` so the
# JIT can resolve out-of-line implementations like `cat::println`.
#
# Modes (auto-selected from arguments and `isatty(stdin)`):
#   * Interactive (default, tty stdin): drops you into the REPL with a
#     "ready" hint. Stdin is relayed through `cat` so input stays
#     line-buffered. `%quit` or Ctrl+D to exit.
#   * Stream (pipe / redirected stdin): no hint, no prompt, code on
#     stdin gets evaluated until EOF.
#   * One-shot (`--eval`): no hint, stdin is ignored, the supplied
#     snippets run in order and the REPL exits.
#
# Flags (consumed by this wrapper before clang-repl ever sees them):
#   --eval CODE         Evaluate CODE. Repeatable; snippets run in order.
#   --eval-file PATH    Same, with snippet sourced from a file.
#   --                  End of wrapper flags. Everything after this is
#                       passed through to clang-repl verbatim.
# Anything else is treated as a clang-repl argument.

set -eEuo pipefail

build_dir='@CMAKE_BINARY_DIR@'
libcat_so="${build_dir}/libcat.so"
flag_extractor='@CMAKE_SOURCE_DIR@/cmake/clang_repl_libcat.py'
interactive_relay='@CMAKE_SOURCE_DIR@/cmake/clang_repl_libcat_interactive.py'
clang_repl='@CAT_CLANG_REPL_EXECUTABLE@'
asan_runtime='@CAT_ASAN_RUNTIME_PATH@'

if [ ! -f "${libcat_so}" ]; then
  echo "clang-repl-libcat: ${libcat_so} not found." >&2
  echo "  Build it first:" >&2
  echo "    cmake --build ${build_dir} --target cat-repl" >&2
  exit 1
fi

evals=()
extra_args=()
while (( $# > 0 )); do
  case "$1" in
    --eval)
      [[ $# -ge 2 ]] || { echo "clang-repl-libcat: --eval needs an argument" >&2; exit 2; }
      evals+=("$2"); shift 2 ;;
    --eval-file)
      [[ $# -ge 2 ]] || { echo "clang-repl-libcat: --eval-file needs a path" >&2; exit 2; }
      [[ -r "$2" ]] || { echo "clang-repl-libcat: cannot read $2" >&2; exit 2; }
      evals+=("$(< "$2")"); shift 2 ;;
    --)
      shift; extra_args+=("$@"); break ;;
    *)
      extra_args+=("$1"); shift ;;
  esac
done

oneshot=0
if (( ${#evals[@]} > 0 )); then
  oneshot=1
fi

mapfile -t flags < <(python3 "${flag_extractor}" "${build_dir}")

# When the build is sanitised, the AddressSanitizer runtime has to be in
# the address space before any JIT-loaded libCat code touches a global,
# otherwise `__asan_init` / `__asan_register_elf_globals` come up
# undefined. `clang-repl` itself is not built with ASan, so preload it
# here. `detect_leaks=0` masks the libedit allocations clang-repl makes
# during its own startup (out of our control). Override by exporting
# ASAN_OPTIONS yourself before invoking the wrapper.
if [ -n "${asan_runtime}" ]; then
  export LD_PRELOAD="${LD_PRELOAD:+${LD_PRELOAD}:}${asan_runtime}"
  : "${ASAN_OPTIONS:=detect_leaks=0}"
  export ASAN_OPTIONS
  echo "[clang-repl-libcat] LD_PRELOAD=${asan_runtime}" >&2
fi

echo "[clang-repl-libcat] preloading ${libcat_so}" >&2
# `clang-repl` sees a pipe on stdin (we feed it `%lib` then relay the
# user's keys through `cat`) and silently suppresses its prompt as a
# result. Surface a one-time ready indicator so interactive users don't
# mistake the silence for a hang. Skip it for non-interactive runs
# (piped stdin or one-shot `--eval`) where there's no human to read it.
if [ -t 0 ] && (( oneshot == 0 )); then
  interactive=1
  echo "[clang-repl-libcat] ready. Type C++; %quit or Ctrl+D to exit." >&2
else
  interactive=0
fi

if (( interactive )); then
  exec python3 "${interactive_relay}" "${libcat_so}" -- \
    "${clang_repl}" "${flags[@]}" "${extra_args[@]}"
fi

# Inject the `%lib` directive ahead of the user's input. Stream mode keeps using
# stdin so pipes and redirects work normally. In one-shot mode, dump the snippets
# and `%quit` so clang-repl evaluates them and exits.
{
  printf '%%lib %s\n' "${libcat_so}"
  if (( oneshot )); then
    for snippet in "${evals[@]}"; do
      printf '%s\n' "${snippet}"
    done
    printf '%%quit\n'
  else
    exec cat
  fi
} | exec "${clang_repl}" "${flags[@]}" "${extra_args[@]}"
